//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4InARowWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int IsOnline { get; set; }
        public int IsPlaying { get; set; }
        public int NumOfgames { get; set; }
        public int NumOfWinning { get; set; }
        public int NumOfLose { get; set; }
    }
}
